"""add status to task

Revision ID: 024ca71c3c7e
Revises: 267bb2aeadf7
Create Date: 2022-02-23 11:03:28.536628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '024ca71c3c7e'
down_revision = '267bb2aeadf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('status', sa.String(), nullable=True))
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_column('tasks', 'status')
    # ### end Alembic commands ###
