"""first revision

Revision ID: 267bb2aeadf7
Revises: 
Create Date: 2022-02-23 10:44:42.839840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '267bb2aeadf7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
