"""commit message

Revision ID: 69470d993ef4
Revises: 
Create Date: 2022-03-16 09:49:34.138304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69470d993ef4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
